# Copyright 2020 The golang.design Initiative authors.
# All rights reserved. Use of this source code is governed
# by a MIT license that can be found in the LICENSE file.

FROM golang:1.15.5
WORKDIR /app
COPY . .
CMD ["/app/midgard", "server"]