// Copyright 2020-2021 Changkun Ou. All rights reserved.
// Use of this source code is governed by a GPL-3.0
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: midgard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingInput) Reset() {
	*x = PingInput{}
	mi := &file_midgard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingInput) ProtoMessage() {}

func (x *PingInput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingInput.ProtoReflect.Descriptor instead.
func (*PingInput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{0}
}

type PingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	GoVersion     string                 `protobuf:"bytes,2,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=BuildTime,proto3" json:"BuildTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingOutput) Reset() {
	*x = PingOutput{}
	mi := &file_midgard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingOutput) ProtoMessage() {}

func (x *PingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingOutput.ProtoReflect.Descriptor instead.
func (*PingOutput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{1}
}

func (x *PingOutput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingOutput) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *PingOutput) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

// AllocateURLInput carries the file to publish, read by the mg command
// rather than by the daemon: the daemon answers any local program, and must
// not open whatever path it is handed.
type AllocateURLInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredPath   string                 `protobuf:"bytes,1,opt,name=DesiredPath,proto3" json:"DesiredPath,omitempty"`
	SourceData    []byte                 `protobuf:"bytes,3,opt,name=SourceData,proto3" json:"SourceData,omitempty"` // empty to publish the universal clipboard
	SourceName    string                 `protobuf:"bytes,4,opt,name=SourceName,proto3" json:"SourceName,omitempty"` // the source file's name, for its extension
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateURLInput) Reset() {
	*x = AllocateURLInput{}
	mi := &file_midgard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateURLInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateURLInput) ProtoMessage() {}

func (x *AllocateURLInput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateURLInput.ProtoReflect.Descriptor instead.
func (*AllocateURLInput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateURLInput) GetDesiredPath() string {
	if x != nil {
		return x.DesiredPath
	}
	return ""
}

func (x *AllocateURLInput) GetSourceData() []byte {
	if x != nil {
		return x.SourceData
	}
	return nil
}

func (x *AllocateURLInput) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type AllocateURLOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateURLOutput) Reset() {
	*x = AllocateURLOutput{}
	mi := &file_midgard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateURLOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateURLOutput) ProtoMessage() {}

func (x *AllocateURLOutput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateURLOutput.ProtoReflect.Descriptor instead.
func (*AllocateURLOutput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{3}
}

func (x *AllocateURLOutput) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *AllocateURLOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CodeToImageInput carries the code itself, for the same reason.
type CodeToImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"` // empty to render the universal clipboard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeToImageInput) Reset() {
	*x = CodeToImageInput{}
	mi := &file_midgard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeToImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeToImageInput) ProtoMessage() {}

func (x *CodeToImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeToImageInput.ProtoReflect.Descriptor instead.
func (*CodeToImageInput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{4}
}

func (x *CodeToImageInput) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CodeToImageOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeURL       string                 `protobuf:"bytes,1,opt,name=CodeURL,proto3" json:"CodeURL,omitempty"`
	ImageURL      string                 `protobuf:"bytes,2,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeToImageOutput) Reset() {
	*x = CodeToImageOutput{}
	mi := &file_midgard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeToImageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeToImageOutput) ProtoMessage() {}

func (x *CodeToImageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeToImageOutput.ProtoReflect.Descriptor instead.
func (*CodeToImageOutput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{5}
}

func (x *CodeToImageOutput) GetCodeURL() string {
	if x != nil {
		return x.CodeURL
	}
	return ""
}

func (x *CodeToImageOutput) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type ListDaemonsInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDaemonsInput) Reset() {
	*x = ListDaemonsInput{}
	mi := &file_midgard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDaemonsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDaemonsInput) ProtoMessage() {}

func (x *ListDaemonsInput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDaemonsInput.ProtoReflect.Descriptor instead.
func (*ListDaemonsInput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{6}
}

type ListDaemonsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daemons       string                 `protobuf:"bytes,1,opt,name=Daemons,proto3" json:"Daemons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDaemonsOutput) Reset() {
	*x = ListDaemonsOutput{}
	mi := &file_midgard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDaemonsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDaemonsOutput) ProtoMessage() {}

func (x *ListDaemonsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_midgard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDaemonsOutput.ProtoReflect.Descriptor instead.
func (*ListDaemonsOutput) Descriptor() ([]byte, []int) {
	return file_midgard_proto_rawDescGZIP(), []int{7}
}

func (x *ListDaemonsOutput) GetDaemons() string {
	if x != nil {
		return x.Daemons
	}
	return ""
}

var File_midgard_proto protoreflect.FileDescriptor

const file_midgard_proto_rawDesc = "" +
	"\n" +
	"\rmidgard.proto\x12\x05proto\"\v\n" +
	"\tPingInput\"b\n" +
	"\n" +
	"PingOutput\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\tR\aVersion\x12\x1c\n" +
	"\tGoVersion\x18\x02 \x01(\tR\tGoVersion\x12\x1c\n" +
	"\tBuildTime\x18\x03 \x01(\tR\tBuildTime\"\x86\x01\n" +
	"\x10AllocateURLInput\x12 \n" +
	"\vDesiredPath\x18\x01 \x01(\tR\vDesiredPath\x12\x1e\n" +
	"\n" +
	"SourceData\x18\x03 \x01(\fR\n" +
	"SourceData\x12\x1e\n" +
	"\n" +
	"SourceName\x18\x04 \x01(\tR\n" +
	"SourceNameJ\x04\b\x02\x10\x03R\n" +
	"SourcePath\"?\n" +
	"\x11AllocateURLOutput\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"N\n" +
	"\x10CodeToImageInput\x12\x12\n" +
	"\x04Code\x18\x04 \x01(\tR\x04CodeJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\bCodePathR\x05StartR\x03End\"I\n" +
	"\x11CodeToImageOutput\x12\x18\n" +
	"\aCodeURL\x18\x01 \x01(\tR\aCodeURL\x12\x1a\n" +
	"\bImageURL\x18\x02 \x01(\tR\bImageURL\"\x12\n" +
	"\x10ListDaemonsInput\"-\n" +
	"\x11ListDaemonsOutput\x12\x18\n" +
	"\aDaemons\x18\x01 \x01(\tR\aDaemons2\x84\x02\n" +
	"\aMidgard\x12-\n" +
	"\x04Ping\x12\x10.proto.PingInput\x1a\x11.proto.PingOutput\"\x00\x12B\n" +
	"\vAllocateURL\x12\x17.proto.AllocateURLInput\x1a\x18.proto.AllocateURLOutput\"\x00\x12B\n" +
	"\vCodeToImage\x12\x17.proto.CodeToImageInput\x1a\x18.proto.CodeToImageOutput\"\x00\x12B\n" +
	"\vListDaemons\x12\x17.proto.ListDaemonsInput\x1a\x18.proto.ListDaemonsOutput\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_midgard_proto_rawDescOnce sync.Once
	file_midgard_proto_rawDescData []byte
)

func file_midgard_proto_rawDescGZIP() []byte {
	file_midgard_proto_rawDescOnce.Do(func() {
		file_midgard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_midgard_proto_rawDesc), len(file_midgard_proto_rawDesc)))
	})
	return file_midgard_proto_rawDescData
}

var file_midgard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_midgard_proto_goTypes = []any{
	(*PingInput)(nil),         // 0: proto.PingInput
	(*PingOutput)(nil),        // 1: proto.PingOutput
	(*AllocateURLInput)(nil),  // 2: proto.AllocateURLInput
	(*AllocateURLOutput)(nil), // 3: proto.AllocateURLOutput
	(*CodeToImageInput)(nil),  // 4: proto.CodeToImageInput
	(*CodeToImageOutput)(nil), // 5: proto.CodeToImageOutput
	(*ListDaemonsInput)(nil),  // 6: proto.ListDaemonsInput
	(*ListDaemonsOutput)(nil), // 7: proto.ListDaemonsOutput
}
var file_midgard_proto_depIdxs = []int32{
	0, // 0: proto.Midgard.Ping:input_type -> proto.PingInput
	2, // 1: proto.Midgard.AllocateURL:input_type -> proto.AllocateURLInput
	4, // 2: proto.Midgard.CodeToImage:input_type -> proto.CodeToImageInput
	6, // 3: proto.Midgard.ListDaemons:input_type -> proto.ListDaemonsInput
	1, // 4: proto.Midgard.Ping:output_type -> proto.PingOutput
	3, // 5: proto.Midgard.AllocateURL:output_type -> proto.AllocateURLOutput
	5, // 6: proto.Midgard.CodeToImage:output_type -> proto.CodeToImageOutput
	7, // 7: proto.Midgard.ListDaemons:output_type -> proto.ListDaemonsOutput
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_midgard_proto_init() }
func file_midgard_proto_init() {
	if File_midgard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_midgard_proto_rawDesc), len(file_midgard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_midgard_proto_goTypes,
		DependencyIndexes: file_midgard_proto_depIdxs,
		MessageInfos:      file_midgard_proto_msgTypes,
	}.Build()
	File_midgard_proto = out.File
	file_midgard_proto_goTypes = nil
	file_midgard_proto_depIdxs = nil
}
