// Copyright 2026 Changkun Ou. All rights reserved.
// Use of this source code is governed by a GPL-3.0
// license that can be found in the LICENSE file.

import AppKit

/// The Mac's clipboard: what is copied on it goes to the other devices, and
/// what arrives from them goes on it. macOS says nothing when the clipboard
/// changes, so it is asked twice a second whether it did, which costs
/// nothing: it keeps a count of changes.
final class LocalClipboard {
    /// The types password managers mark a copy with, by the convention of
    /// nspasteboard.org: such a copy is not synced, nor kept.
    static let secret: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    let board: NSPasteboard
    /// Called with each copy made on this Mac, as a midgard type ("text" or
    /// "image/png") and its bytes.
    var onCopy: ((String, Data) -> Void)?

    private var seen: Int
    private var timer: Timer?

    init(_ board: NSPasteboard = .general) {
        self.board = board
        seen = board.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Looks for a change, and hands it on. What midgard wrote itself is not
    /// a change: it came from another device.
    func poll() {
        guard board.changeCount != seen else { return }
        seen = board.changeCount
        if let (mime, data) = read() { onCopy?(mime, data) }
    }

    /// What is on the clipboard, if it is something midgard syncs and not a
    /// secret: text, or an image as PNG.
    func read() -> (String, Data)? {
        let types = Set(board.types ?? [])
        if !types.isDisjoint(with: LocalClipboard.secret) { return nil }
        if let s = board.string(forType: .string), !s.isEmpty {
            return ("text", Data(s.utf8))
        }
        if let png = board.data(forType: .png) {
            return ("image/png", png)
        }
        if let tiff = board.data(forType: .tiff), let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            return ("image/png", png)
        }
        return nil
    }

    /// Puts a copy on the clipboard.
    func write(mime: String, data: Data) {
        board.clearContents()
        switch mime {
        case "text":
            board.setString(String(decoding: data, as: UTF8.self), forType: .string)
        case "image/png":
            board.setData(data, forType: .png)
        default:
            return
        }
        seen = board.changeCount
    }
}
